title: IT Gateway
description: Comprehensive IT theory and practical resource for Grade 10-12
theme: jekyll-theme-just-the-docs

# Color scheme - blue theme
color_scheme: blue

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3

# Navigation
nav_sort: case_insensitive
nav_external_links:
  - title: Google Classroom
    url: https://classroom.google.com
    hide_icon: false

# Enable features
enable_copy_code_button: true
back_to_top: true
back_to_top_text: "Back to top"

# Footer
footer_content: "IT Gateway - Your bridge between theory and practice © 2025"

# Plugins
plugins:
  - jekyll-default-layout
  - jekyll-seo-tag
