# EMERGENCY FIX - Replace _config.yml Completely

## The Problem
Your `_config.yml` still contains `theme: jekyll-theme-just-the-docs` which GitHub Pages doesn't support.

## IMMEDIATE SOLUTION

### Step 1: Delete Everything in _config.yml
**Open your `_config.yml` file in VS Code and delete ALL content**

### Step 2: Replace with This EXACT Content
```yaml
title: IT Gateway
description: Comprehensive IT theory and practical resource for Grade 10-12

# Use ONLY themes supported by GitHub Pages
theme: minima

# Basic settings
url: "https://yourusername.github.io"
baseurl: "/it-gateway"

# Plugins (only GitHub Pages supported ones)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation
header_pages:
  - fundamentals/index.md
  - systems/index.md
  - networks/index.md
  - programming/index.md
  - exam-prep/index.md

# Exclude files
exclude:
  - README.md
  - "*.py"
```

### Step 3: Save and Push
```bash
git add _config.yml
git commit -m "Fix theme for GitHub Pages compatibility"
git push
```

## Alternative: Use Remote Theme
If you want better styling, replace the `theme: minima` line with:
```yaml
remote_theme: pmarsceill/just-the-docs
```

## What Was Wrong
- GitHub Pages only supports these themes by default: minima, slate, leap-day, architect, cayman, dinky, hacker, merlot, midnight, minimal, modernist, tactile, time-machine
- `jekyll-theme-just-the-docs` is NOT in that list
- Using `remote_theme` is the workaround for unsupported themes

## Quick Test
After pushing, wait 2-3 minutes and check:
`https://yourusername.github.io/it-gateway`

If it still fails, try the `remote_theme` approach instead.

## Nuclear Option (If Nothing Works)
Create a completely minimal `_config.yml`:
```yaml
title: IT Gateway
description: IT Gateway Website
```

This will use GitHub's absolute defaults and WILL work.

**The key is removing ANY reference to `jekyll-theme-just-the-docs`!**