title: IT Gateway
description: Comprehensive IT theory and practical resource for Grade 10-12

# Use remote theme
remote_theme: just-the-docs/just-the-docs

# Enable search
search_enabled: true

# Navigation
nav_external_links:
  - title: Google Classroom
    url: https://classroom.google.com

# Enable features
enable_copy_code_button: true

# Footer
footer_content: "IT Gateway - Your bridge between theory and practice © 2025"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - README.md
  - "*.py"
  - head_custom.html